platform: "tensorrt_plan"
name : "scrfd"
max_batch_size: 16
input [
  {
    name: "input.1"
    data_type: TYPE_FP32
    format:FORMAT_NCHW
    dims: [3,320,320]
  }
]
output [
  {
    name: "bbox_16"
    data_type: TYPE_FP32
    dims: [800,4]
  },
  {
    name: "bbox_32"
    data_type: TYPE_FP32
    dims: [200,4]
  },
  {
    name: "bbox_8"
    data_type: TYPE_FP32
    dims: [3200,4]
  },
  {
    name: "kps_16"
    data_type: TYPE_FP32
    dims: [800,10]
  },
  {
    name: "kps_32"
    data_type: TYPE_FP32
    dims: [200,10]
  },
  {
    name: "kps_8"
    data_type: TYPE_FP32
    dims: [3200,10]
  },
  {
    name: "score_16"
    data_type: TYPE_FP32
    dims: [800,1]
  },
  {
    name: "score_32"
    data_type: TYPE_FP32
    dims: [200,1]
  },
  {
    name: "score_8"
    data_type: TYPE_FP32
    dims: [3200,1]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]